In [127]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [128]:
df_partidas = pd.read_csv('../data/trusted/base_partidas_trusted.csv')
df_jogadores = pd.read_csv('../data/trusted/dm_jogadores.csv')
df_times = pd.read_csv('../data/trusted/dm_times.csv')

In [ ]:
df_partidas.head(1)

,id_partida,datetime,id_torneio,nome_torneio,id_estadio,token_estadio,nome_estadio,id_player_casa,nome_player_casa,gols_casa,id_time_casa,nome_time_casa,id_player_fora,nome_player_fora,gols_fora,id_time_fora,nome_time_fora,data,hora_brt,hora_us,resultado,gols_total,id_resultado
0,1404256,2025-01-01T11:50:00Z,181773,Champions League A 2x6 2025-01-01,136,Anfield-1,Anfield-1,113,flamez,3,21,Paris Saint-Germain F.C.,112,Kinshiki,3,6,Manchester City,01/01/2025,11:50,08:50,empate,6,0

In [130]:
df_jogadores.head(1)

,id_player,nome_player,total_gols_player,total_partidas_player,total_vitorias_player,total_derrotas_player,total_empates_player,media_gols_player,winrate_player,lossrate_player,drawrate_player,saldo_player,ratio_vd_player,invencibilidade_player
0,1,Kolesya,19070,8446,3640,2918,1888,2.257874,0.430973,0.345489,0.223538,722,1.247002,0.654511

In [133]:
df_times.head(1)

,id_time,nome_time,total_gols_time,total_partidas_time,total_vitorias_time,total_derrotas_time,total_empates_time,media_gols_time,winrate_time,lossrate_time,drawrate_time,saldo_time,ratio_vd_time,invencibilidade_time
0,2,Liverpool,43052,16768,6348,6528,3892,2.56751,0.378578,0.389313,0.232109,-180,0.972278,0.610687